apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
        - name: payment-service
          image: santyet/payment-service:latest
          ports:
            - containerPort: 8800
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: EUREKA_INSTANCE
              value: "payment-service"
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service
spec:
  selector:
    app: favourite-service
  ports:
    - protocol: TCP
      port: 8800
      targetPort: 8800
  type: ClusterIP
